import SignOut from "@/components/SignOut";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col">
          <Link href="/auth-server-action">Auth Server Action</Link>
          <Link href="/">home</Link>
          <Link href="/todo">Learn CRUD</Link>
          <SignOut />
        </div>
        {children} <Toaster />
      </body>
    </html>
  );
}
